### ISSUE TITLE
Native Ingress support

### ISSUE THREAD

**Issue by Salvora** [hassio-addons/addon-bookstack#141]
# Problem/Motivation

Add ingress support as stated in https://github.com/hassio-addons/addon-bookstack/issues/2

## Expected behavior

An option to the add-on for ingress.

## Actual behavior

was not supported previously

## Proposed changes

Currently, this can be done by adding an env var to the addon configuration
```yaml
envvars:
  - name: ALLOWED_IFRAME_HOSTS
    value: https://homeassistant.xxx.org
```

Using panel_iframe to add it.
```yaml
panel_iframe:
  bookstack:
    title: "BookStack"
    url: "https://bookstack.xxx.org"
    icon: mdi:stack-overflow
```
bookstack.xxx.org is created by nginx which maps it to https://homeassistant.xxx.org:2665
though replacing the url with https://homeassistant.xxx.org:2665 should work.
A native option could be nice but the same result can be achieved with the above options anyway.
