### ISSUE TITLE
Add "Show in sidebar" option

### ISSUE THREAD

**Issue by github-cyprien** [hassio-addons/addon-bookstack#225]
# Problem/Motivation

> The addon do not have a "Show in sidebar" option like other addons, we need to click on "Open web UI" to use bookstack

**Comment by github-cyprien** [comment]
Ok, sorry, for that issue...

**Comment by frenck** [comment]
Don't worry about it 👍

**Comment by kozfelipe** [comment]
for anyone wanting to use it as an iframe
_configutation.yaml_
```
panel_iframe:
    bookstack:
        title: "Wiki"
        icon: mdi:wikipedia
        url: "http://[[bookstack ip]]:2665/?iframe=true&theme=dark"
        require_admin: true
```
_addons -> bookstack -> configuration_
```
envvars:
  - name: ALLOWED_IFRAME_HOSTS
    value: http://[[hass-io ip]]:8123
  - name: SESSION_SECURE_COOKIE
    value: "true"
```
