### ISSUE TITLE
Allow changing the user session timeout?

### ISSUE THREAD

**Issue by CodeFinder2** [hassio-addons/addon-bookstack#23]
Hi!

is it possible to change the following somehow through the addon config or can it be added in a future release?

https://github.com/BookStackApp/BookStack/blob/16d8a667b164b60623785ab89f8a1db41fd8b680/.env.example.complete#L69

BookStacks only runs locally, so I would like to extend the session timeout as much as possible because I don't want to login over and over again. :-) (Or is it even possible to disable the login somehow?)

Follow up question; isn't it possible to add BookStack as an iframe? Like (`configuration.yaml`):
```yaml
panel_iframe: 
  bookstack:
    title: BookStack
    icon: mdi:wikipedia
    url: http://home:2665/
```

Thanks!
