### ISSUE TITLE
Feature Request: Tighter intergation way (kind of ingress)

### ISSUE THREAD

**Issue by rabits** [hassio-addons/addon-bookstack#322]
# Problem/Motivation

Spent quite a bit of time trying to integrate bookstack into home assistant with menu record and https nginx proxy

## Expected behavior

Probably there is a way to setup it by default the way it will properly redirect even the uploaded images through home assistant proxy and will be more stable and available from the remote proxy.

## Actual behavior

For now there are 3 issues with this complicated setup:
1. Works only with full path in APP_URL which limits the ability to use chained reverse proxies (one local proxy to serve HA via https and wifi connection and another remote proxy when you on a road)
2. If I try to upload an image or switch the Light/Dark mode - it's not updating the iframe to show the changes (works well if I switch on https://ha.local/bookstack/)
3. Many pages cached in different states, no cache disable helps

## Steps to reproduce

1. Install Bookstack addon as usual (with mariadb) + add the next envvars into:
```yaml
- name: APP_URL
  value: https://your-ha.local/bookstack  # In theory here should be something like "/bookstack", but it's not working so binding to local - so will be unavailable from remote proxy...
- name: STORAGE_URL
  value: /bookstack_storage  # To make the upload of images/files bind to whatever domain you use
- name: ALLOWED_IFRAME_HOSTS
  value: https://your-ha.local https://your-ha.remote.com
```
3. Install & configure NGINX Home Assistant SSL proxy addon (when generate ssl certs make sure to use DNS-Altnames & add certs as trusted to android CA to use with companion app)
4. Install Ingress addon through HACS & configure it to show the bookstack item in the HA menu: /config/configuration.yaml , reread it after update
```yaml
# Custom ingress menu fields
ingress:
  wiki:
    work_mode: iframe  # Ingress shows no menu, so iframe helps here
    ui_mode: toolbar
    title: BookstackWiki
    icon: mdi:book
    url: /bookstack/
```
5. Prepare new locations for nginx addon: /share/nginx_proxy_default_wiki_page.conf
```
location /bookstack {
    rewrite /bookstack/bookstack_storage/(.*) /$1  break;
    rewrite /bookstack/(.*) /$1  break;

    proxy_pass http://a0d7b954-bookstack/;
    proxy_set_header Host $http_host;
    proxy_redirect http:// https://;
    proxy_http_version 1.1;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Forwarded-Host $http_host;
}

# Special override for bookstack storage (images, etc...)
location /bookstack_storage {
    rewrite /bookstack_storage/(.*) /$1  break;

    proxy_pass http://a0d7b954-bookstack/;
    proxy_set_header Host $http_host;
    proxy_redirect http:// https://;
    proxy_http_version 1.1;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Forwarded-Host $http_host;
}
```
6. Restart nginx addon
7. Test how it's working - if you will upload picture it will be written to the database with `/bookstack_storage` prefix, which works for us just well.
