### ISSUE TITLE
BookStack does not work in an iframe

### ISSUE THREAD

**Issue by CodeFinder2** [hassio-addons/addon-bookstack#35]
As already described in #23, using the addon (v0.8.0) within an iframe doesn't work.
This is my addon config:
```yaml
envvars:
  - name: ALLOWED_IFRAME_HOSTS
    value: 'http://hassio'
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
```

And this is my iframe entry in configuration.yaml:
```yaml
bookstack:
  title: BookStack
  icon: mdi:wikipedia
  url: http://hassio:2665/
``` 

Error message (Chrome):
```
Refused to frame 'http://hassio:2665/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

Also tested `http://hassio`, `http://hassio/` and `http://hassio:2665/` as `value` which didn't work too.

EDIT: Still not working in v0.8.1.
