### ISSUE TITLE
custom environment variables are overwritten

### ISSUE THREAD

**Issue by m4t7** [hassio-addons/addon-bookstack#73]
# Problem/Motivation

After adding other environment variables , the respective config is reset when saving the configuration.

## Expected behavior

Set several environment variables and save them as specified in the documentation.

## Actual behavior

This is the addon configuration I have attached

```
envvars:
  - name: SESSION_COOKIE_NAME
    value: bookstack_session
  - name: SESSION_LIFETIME
    value: 120
  - name: APP_DEFAULT_DARK_MODE
    value: true
  - name: AVATAR_URL
    value: false
  - name: DRAWIO
    value: false
proxy_host: private.host.name
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
log_level: debug
```

After clicking save and then addon restart, only one environment variable is set again.

```
envvars:
  - name: SESSION_COOKIE_NAME
    value: bookstack_session
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
proxy_host: private.host.name
log_level: debug
```

## Steps to reproduce

Add other env. variable(s).

```
envvars:
  - name: SESSION_COOKIE_NAME
    value: bookstack_session
  - name: SESSION_LIFETIME
    value: 120
  - name: APP_DEFAULT_DARK_MODE
    value: true
  - name: AVATAR_URL
    value: false
  - name: DRAWIO
    value: false
```

## Proposed changes

I assume that the options and schema entries in the config.json file would need to be modified to fix the problem.
